* Overtone Sylt

Sylt is an environment for networked collaborative noise exploration using
Overtone.


** How does it work?

Overtone, jackd, and vlc are packaged inside a Docker container.

- Overtone manages most of the collaborative noise exploration part.
Overtone exposes a Gorilla web-repl, and an nrepl.

- jackd is a dependency of Overtone, and is a sound server

- vlc is used to communicate with jackd over the network

** Build and run
- clone repo
git clone https://github.com/jave/overtone-sylt.git

- build the docker
docker build -t sylt .

- run the docker
docker run  -v /tmp/m2:/root/.m2/ -p 3000:3000 -p 32768:32768 -p 9999:9999 -p 1234:1234/udp -it sylt

- start the gorilla repl
http://<host>:8080/worksheet.html?filename=sylt

<host> is the server where Sylt is running.

- load startup code, which is already in the repl
(load-file "/insane-noises/src/insane_noises/core.clj")

- start some noise
(insane-noises.core/play-drums 100 16)

- Listen to the noise
mplayer rtsp://<host>:9999/test.sdp

<host> is the server where Sylt is running.

** building janus

** running with janus

# start janus
docker run -it -p 5002:5002/tcp -p 5002:5002/udp -p 5004:5004/tcp -p 8088:8088/tcp -p 7088:7088/tcp -p 5004:5004/udp -p 8188:8188/tcp f18e   /opt/janus/bin/janus -p 8088 -S stun.ekiga.net


** tested rtsp players
- vlc beta android, lan
- mplayer, lan
** The name
Sylt means Jam in Swedish. This joke is no worse than the Leiningen
joke. Well okay, it's worse. Every conceivable variation of
"jamming/network/web" was of course already occupied on the noosphere.

